# Generated by Django 4.2.3 on 2026-04-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio_profile_birth_date_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Не указан'), ('single', 'Не женат / Не замужем'), ('dating', 'Встречается'), ('engaged', 'Помолвлен(а)'), ('married', 'Женат / Замужем'), ('complicated', 'Всё сложно'), ('searching', 'В активном поиске'), ('in_love', 'Влюблён(а)')], default='', max_length=16),
        ),
    ]
